### ISSUE TITLE
NotFoundError: waymo_labelmap.txt; No such file or directory

### ISSUE THREAD

**Issue by gopikrishnabs** [raz4/waymo-object-detection#1]
while executing the below command:
def get_num_classes(pbtxt_fname):
    from object_detection.utils import label_map_util
    label_map = label_map_util.load_labelmap(pbtxt_fname)
    categories = label_map_util.convert_label_map_to_categories(
        label_map, max_num_classes=90, use_display_name=True)
    category_index = label_map_util.create_category_index(categories)
    return len(category_index.keys())
num_classes = get_num_classes(label_map_path)
num_classes

MODELS_CONFIG = {
    'efficientdet_d7': {
        'model_name': 'efficientdet_d7_coco17_tpu-32',
        'base_pipeline_file': 'efficientdet_d7_coco17_tpu-32.config',
        'pretrained_checkpoint': 'efficientdet_d7_coco17_tpu-32.tar.gz',
        'batch_size':7
    },
    'efficientdet_d4': {
        'model_name': 'efficientdet_d4_coco17_tpu-32',
        'base_pipeline_file': 'efficientdet_d4_coco17_tpu-32.config',
        'pretrained_checkpoint': 'efficientdet_d4_coco17_tpu-32.tar.gz',
        'batch_size':14
    }
}

chosen_model = 'efficientdet_d4'
num_steps = 50000
num_eval_steps = 500

model_name = MODELS_CONFIG[chosen_model]['model_name']
pretrained_checkpoint = MODELS_CONFIG[chosen_model]['pretrained_checkpoint']
base_pipeline_file = MODELS_CONFIG[chosen_model]['base_pipeline_file']
batch_size = MODELS_CONFIG[chosen_model]['batch_size']
pipeline_fname = './'+ model_name + '/pipeline.config'
fine_tune_checkpoint = './' + model_name + '/checkpoint/ckpt-0'
label_map_path = **'waymo_labelmap.txt'**
train_record_fname = "./waymo_data_v120/training/*"
test_record_fname = "./waymo_data_v120/validation/*"

I am not knowing where the text file waymo_labelmap is present.

I am unable to locate where this file is can anyone kindly reply to me thanks.

**Comment by raz4** [comment]
@gopikrishnabs Seems like I didn't add that file. You can create the file with the following contents:
```
item {
  id: 1
  name: 'Vehicles'
}

item {
  id: 2
  name: 'Pedestrians'
}

item {
  id: 3
  name: 'Cyclists'
}
```

**Comment by gopikrishnabs** [comment]
Thanks for answering. I did add the file.
